### ISSUE TITLE
Admin user name and password

### ISSUE THREAD

**Issue by ckdoty01** [gnuedcl/dcl#6]
Sorry about this but I just did a clean install and I am not able to log into the default admin account.  Can someone please let me know what the default user name and password is?

**Comment by mdean** [comment]
The default is sa / sa.

**Comment by ckdoty01** [comment]
I read that in the documentation but cant get it to work on a clean install.  I am wondering if I am having a different issue.

When I try that I get "Invalid login or password"

**Comment by mdean** [comment]
What type of SQL database are you using?

**Comment by ckdoty01** [comment]
I am using mySQL on a ubuntu box. 14.04

**Comment by vgupta619** [comment]
I am also using MySql and having same issue, I can't login using user: sa and Password: sa

**Comment by mdean** [comment]
I just added a couple of fixes to fresh MySQL installations.  I was able to login with the default credentials using MySQL 5.5.  d6d5a808a6ea9ec438126ff3a9587768c1402bf9
